project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating
  body-footer: Made by [Kurian Benoy](https://kurianbenoy.com/). See the [code.](https://github.com/kurianbenoy/malayalam_asr_benchmarking)

metadata-files: [nbdev.yml, sidebar.yml]
